target_devices:
  - name: Kitchen
    # required: true
    # main: true
  - name: Move 2
    # main: true
    # required: false
  - name: Front Room
    required: true
    main: true
  - name: "Family Room (TV)"
    required: false

connection:
  reconnect_time: 15

