target_devices:
  - name: Kitchen
    required: true
    main: false
  - name: Move 2
    main: false
    required: false
  - name: Front Room
    required: true
    main: true
  - name: "Family Room (TV)"
    required: false
    main: false
